var e;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&"html"==document.documentElement.localName){window.__idm_init__=!0;Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});Array.prototype.F||(Array.prototype.F=function(a){0>a&&(a+=this.length);return this[a]});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);
"undefined"==typeof browser&&(browser=chrome);navigator.userAgent.includes("Edge/");navigator.userAgent.includes("Firefox/");navigator.userAgent.includes("OPR/");var w=Object.values,y=RegExp.prototype.test,E=Array.from,F=Array.prototype.includes,G=Function.call.bind(Array.prototype.slice),I=Function.apply.bind(Array.prototype.push),J=Function.call.bind(Array.prototype.forEach),K="dotAll"in RegExp.prototype?"s":"",L={16:!0,17:!0,18:!0,45:!0,46:!0},M=F.bind(["video","audio","object","embed"]),N=/(?!)/,
O=/ *[$~]([<>{}&*+=@|!#%:?^~-])(\d*) */,T=y.bind(/^rgba?\(\d+,\s*\d+,\s*\d+,\s*0\)/),U=window.self===window.top,V=window.origin||document.origin||location.origin,W=location.hostname.toLowerCase()+location.pathname+location.search,X=location.hostname.toLowerCase().split(".").F(-2),Y="idmrs://"+X+"/",aa=X?RegExp("^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*"+X+"$","i"):N;function P(){browser.runtime.Wa?this.$=browser.runtime.Wa(window):U&&(this.$=0);this.ea=[];this.aa=[];this.u=new Map;this.c={};this.Ta();
window.__idm_connect__=this.Ta.bind(this,!0);this.b(1,window,"resize",this.Vb);this.b(1,window,"scroll",this.Wb);this.b(1,window,"blur",this.Nb);this.b(1,window,"keydown",this.ab,!0);this.b(1,window,"keyup",this.ab,!0);this.b(1,window,"mousedown",this.Pb,!0);this.b(1,window,"mouseup",this.Rb,!0);this.b(1,window,"mousemove",this.Qb,!0);this.b(1,window,"click",this.Ob,!0);this.b(1,document,"beforeload",this.Lb,!0);this.b(1,document,"DOMContentLoaded",this.$a);"interactive"!=document.readyState&&"complete"!=
document.readyState||this.$a()}e=P.prototype;e.i=0;e.s=0;e.ha=-1;e.ia=-1;e.hb=1;e.P=0;e.g="";e.Da="";e.H="";e.Ja=N;e.Oa=N;e.I=N;e.Qa=/^\/(?:watch\?(?:.*?&)?v=|shorts\/|embed\/)([\w-]{10,12})(?:[/?&#]|$)/;e.D={};e.Ka=N;e.La=N;e.Ma=N;e.Na=N;e.Pa='$> *[role="main"]:not(hidden) video';e.S="$< div#inline-preview-player $< a#media-container-link";e.Ra=RegExp('"PLAYER_JS_URL":\\s*"(.*?)"',K);e.ra=N;e.ma=":root:empty";e.pa='div[id^="mount_0_"] >div:is([class=""],:not([class])) >div[class=""] >div:first-child';
e.m=":root:empty";e.qa=":root:empty";e.B=":root:empty";e.o="$< div >:not(:only-child):not(video:first-child,img:first-child:nth-last-child(2)) <";e.sa="$> div[data-video-id] $= data-video-id";e.la="a:not([target])";e.C=":root:empty";e.oa=4;e.na=N;e.ua=N;e.Ba=":root:empty";e.va='$& div.xxzkxad $& section main[role="main"] $& div.xw7yly9 >div >div[style]:only-child $& div >article <';e.ya='$& div.xxzkxad $& section main[role="main"] $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';
e.Ca="$& div.xxzkxad $& section.x5qyhuo $& :scope >div >div:only-child $& section >div";e.ta='$+ article:scope $* main[role="main"] article';e.xa='$& div[role="dialog"] div[role="dialog"] >div $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';e.R="$* video";e.za='$= poster ${ div[role="presentation"] >div >ul $<< $>:scope >div[data-instancekey] img $= src';e.Aa="*.return.return.memoizedProps.videoFBID";e.wa=/\/(?:p|reel)\/([\w-]{11})(?:[/?#]|$)/;e.Ea=N;e.Fa=
/^(?:[^/]+|player\.vimeo\.com\/video)\/(\d{2,})/;e.Ia="$| video:scope $| video";e.Ga="$> :scope >div.player";e.Ha="$& div.vp-video $& div.vp-telecine";e.Ta=function(a){this.cb(-1);this.a=a=browser.runtime.connect({name:(U?"top":"sub")+(a?":retry":"")+("file:"==location.protocol?":file":"")});this.b(-1,a,"onMessage",this.Tb);this.b(-1,a,"onDisconnect",this.Sb)};e.Sb=function(){browser.runtime.lastError;this.cb();this.a=this.ba=null;window.__idm_init__=!1;window.__idm_connect__=null};e.Tb=function(a){switch(a.shift()){case 11:this.vb.apply(this,
a);break;case 17:this.wb.apply(this,a);break;case 12:this.xb.apply(this,a);break;case 13:this.nb=a.shift();break;case 14:this.Ab.apply(this,a);break;case 15:this.Bb.apply(this,a);break;case 16:this.Cb.apply(this,a);break;case 18:this.zb.apply(this,a)}};e.Yb=function(a,b){var c=94<=this.lb;switch(this.f=a){case 1:this.h=this.ob=!0;if(a=b.shift())this.g=a;if(a=b.shift())this.Ja=RegExp(a,K);if(a=b.shift())this.I=RegExp(a);if(a=b.shift())this.Qa=RegExp(a);if(a=b.shift())this.D=a.split(/[|:]/).reduce(ba,
{});if(a=b.shift())this.Ka=RegExp(a);if(a=b.shift())this.La=RegExp(a,K);if(a=b.shift())this.Ma=RegExp(a,K);if(a=b.shift())this.Na=RegExp(a,K);if(a=b.shift())this.Oa=RegExp(a,K);if(a=b.shift())this.Pa=a;if(a=b.shift())this.S=a;if(a=b.shift())this.Ra=RegExp(a,K);break;case 2:this.h=!0;if(a=b.shift())this.g=a;if(a=b.shift())this.H=a;if(a=b.shift())this.ra=RegExp(a);if(a=b.shift())this.ma=a;(a=b.shift())&&c&&(this.pa=a);b.shift();if(a=b.shift())this.m=a;if(a=b.shift())this.qa=a;if(a=b.shift())this.B=
a;if(a=b.shift())this.o=a;if(a=b.shift())this.sa=a;if(a=b.shift())this.la=a;if(a=b.shift())this.C=a;(a=b.shift())&&c&&(this.oa=a);if(a=b.shift())this.jb=a;if(a=b.shift())this.na=RegExp(a);break;case 4:this.h=!0;if(a=b.shift())this.g=a;if(a=b.shift())this.Da=a;if(a=b.shift())this.H=a;if(a=b.shift())this.ua=RegExp(a);if(a=b.shift())this.Ba=a;if(!c)break;if(a=b.shift())this.va=a;if(a=b.shift())this.ya=a;if(a=b.shift())this.Ca=a;if(a=b.shift())this.ta=a;if(a=b.shift())this.xa=a;if(a=b.shift())this.R=
a;if(a=b.shift())this.za=a;b.shift();if(a=b.shift())this.Aa=a;if(a=b.shift())this.wa=RegExp(a);break;case 3:if(a=b.shift())this.Ea=RegExp(a);if(a=b.shift())this.Fa=RegExp(a);if(a=b.shift())this.Ia=a;if(a=b.shift())this.Ga=a;if(a=b.shift())this.Ha=a;break;case 5:this.h=!0;if(a=b.shift())this.g=a;if(a=b.shift())this.H=a;if(a=b.shift())this.mb=a;break;default:this.h=!0;if(a=b.shift())this.g=a;if(a=b.shift())this.ka=a}this.g.includes("^/")&&((b=this.Da)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||
void 0):b=V.replaceAll(".","\\."),this.g=this.g.replaceAll("^/","^(?:"+b+")?/"))};e.Y=function(a){if(this.f&&this.O(arguments))switch(this.f){case 1:this.Kb(a);break;case 2:this.Gb(a);break;case 4:this.Hb(a);break;case 3:this.Jb(a);break;case 5:this.Ib(a)}};e.U=function(a){var b=this.a,c;for(c of document.getElementsByTagName("script"))!c.src&&a.test(c.textContent)&&b.postMessage([34,null,-1,c.textContent]);b.postMessage([34,this.G()])};e.bb=function(a,b,c){if(this.ib&&b){var d=this.M(a);if(d){this.u.set(a,
c);window.postMessage([1229212980,d,b],"/");return}}c(a)};e.Ub=function(a,b){if(a=this.c[a]){var c=this.u.get(a);c&&(this.u.delete(a),c(a,b))}};e.Xb=function(a){var b=a.data;if(Array.isArray(b)&&a.origin==V)switch(b[0]){case 1229212977:window.postMessage([1229212978,this.ba,this.h,this.ob,this.g,this.H],"/");this.ib=!0;break;case 1229212979:this.a.postMessage([36,b[1],b[2]]);break;case 1229212981:this.Ub(b[1],b[2])}};e.V=function(){var a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;
b&&c&&(a=b==c?0:b/c);return a};e.M=function(a){var b=a.l;b||(b=a.l=this.ba<<13|this.hb++,a.setAttribute("__idm_id__",b),this.c[b]=a);return b};e.K=function(a){a.v&&(window.clearTimeout(a.v),a.v=null);a.f&&(a.f.disconnect(),a.f=null);this.N&&this.N.unobserve(a);this.j&&this.j.unobserve(a);delete this.c[a.l];a.l=a.c=a.a=null};e.Sa=function(a,b,c){var d=this.M(a);if(b||c){for(var f of w(this.c))if(b?b==f.c:c==f.a)return;a.a=c||Y+a.localName+"/"+b;a.c=b}a.f||(b=a.f=new MutationObserver(this.ca.bind(this)),
b.observe(a,{attributes:!0,attributeFilter:["style"]}),b.observe(a.parentElement,{childList:!0}),this.N&&this.N.observe(a));1==this.f&&t(a,this.S)&&(a.j=!0,a.u=10);return d};e.A=function(a,b,c,d){if(b=this.Sa(a,b,c))d&&this.j&&this.j.observe(a),d=this.L(a),this.a.postMessage([41,b,a.localName,a.src||a.data,a.a,a.c,d])};e.ub=function(a,b,c,d,f,h){var m,l,p,k=window.getComputedStyle.bind(window);try{var g=0;var q=document.activeElement;q&&M(q.localName)||(q=document.elementFromPoint(this.ha,this.ia))&&
!M(q.localName)&&(q=null);for(var n of document.querySelectorAll("video,audio,object,embed")){var r=n.localName,u,v="object"==r||"embed"==r;if(v){var C=n.type.toLowerCase();if(C.startsWith("text/")||C.startsWith("image/"))continue;if("embed"==r&&"application/x-shockwave-flash"!=C)continue}if(n.a&&!n.j&&(f||h))if(f?f==n.c:h==n.a)var x=n;else continue;else if(u=n.src||n.data)u!=a&&u!=b||(x=n);else if(!v)for(var H of n.getElementsByTagName("source"))if((u=H.src)&&(u==a||u==b)&&(x=n))break;if(x)if("cover"==
k(n).objectFit){var z=n;x=null}else break;if(!(z||q||m)){if(u){if((u==c||u==d)&&(m=n))continue;if("video"==r&&u.startsWith("data:audio/"))continue}var A=n.clientWidth,D=n.clientHeight;if(A&&D){var Q=n.getBoundingClientRect();if(!(0>=Q.right+window.scrollX||0>=Q.bottom+window.scrollY))if("hidden"==k(n).visibility||n.W)"video"==r&&(p||(p=n));else{v=A*D;if(g<v&&1.35*A>D&&A<3*D){g=v;var ca=n}l||(l=n)}}}}}catch(da){}(n=x||z||q||m)?"video"!=n.localName&&"hidden"==k(n).visibility&&(n=null):n=ca||l||p;n&&
("embed"!=n.localName||n.clientWidth||n.clientHeight||(a=n.parentElement,"object"==a.localName&&(n=a)),this.Sa(n,f,h));return n};e.tb=function(a,b,c){var d=null,f,h=browser.runtime.Wa,m;for(m of document.getElementsByTagName("iframe")){var l=m.h;null==l&&h&&(l=m.h=h(m));if(l==a){d=m;break}else d||!(f=m.src)||f!=b&&f!=c||(d=m)}return d&&this.M(d)};e.L=function(a){var b=null;try{var c=window.getComputedStyle(a),d=a.getBoundingClientRect(),f=this.P,h=Math.round(d.width),m=Math.round(d.height);if("hidden"==
c.visibility&&!a.contentWindow)return h>5*m?null:!1;if(0==c.opacity||a.W)return!1;if(1==this.f&&0==a.offsetTop+a.offsetHeight){for(var l=a;l=l.parentElement;){var p=window.getComputedStyle(l);if("block"!=p.display)break;if(0==p.opacity)return!1}d=a.parentElement.parentElement.getBoundingClientRect();f=0}var k=Math.round(d.left)+a.clientLeft,g=Math.round(d.top)+a.clientTop,q=d=0;l=a;p=c;for(var n,r;f--&&"block"==p.display&&(n=l.parentElement)&&"div"==n.localName;l=n,p=r){r=window.getComputedStyle(n);
d-=l.offsetLeft;q-=l.offsetTop;if("hidden"==r.overflowX){var u=h-n.offsetWidth-d;0<d&&(h-=d,k+=d);0<u&&(h-=u);f=0}if("hidden"==r.overflowY){var v=m-n.offsetHeight-q;0<q&&(m-=q,g+=q);0<v&&(m-=v);f=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.a||1>a.readyState&&2==a.networkState)&&(b=!1);if(15>h||10>m)return b;break;case "audio":if(1>h&&1>m)return b;var C=!0}var x=document.documentElement,H=x.scrollWidth||x.clientWidth,z=x.scrollHeight||x.clientHeight;if(k>=H||g>=z||C&&
!k&&!g)return b;0==k&&g==-z&&h==H&&m==z&&(g=0);var A=this.V();q=a.u||0;b=[k,g+q,k+h,g+m-q,A]}catch(D){}return b};e.pb=function(a){var b=a.Db;if(b){b=document.elementsFromPoint((b.left+b.right)/2,(b.top+b.bottom)/2);for(var c,d;(c=b.shift())&&!c.isSameNode(a);){var f=window.getComputedStyle(c);if("visible"==f.visibility&&"0"!=f.opacity&&!T(f.backgroundColor)){d=!0;break}}a.W=d}};e.G=function(){var a=U?80:90;try{var b=window.top.document.title}catch(c){}b||(b=(b=document.head.querySelector('meta[property="og:title"]'))&&
b.getAttribute("content"),a=70);b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),b=new String(b.trim()),b.src=a);return b};e.yb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement,b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0),d=0,f=0,h=0,m;for(m of c)if(m.offsetWidth>=b){var l=window.getComputedStyle(m);.95<=l.opacity&&(c=l.zIndex,"fixed"==l.position?(l=m.offsetHeight+m.offsetTop,d<l&&l<a&&
(d=l,f=c)):h<c&&(h=c))}f<h&&(d=0);return d};e.vb=function(a,b,c,d,f,h,m,l,p){l&&R("text/javascript",l);this.lb=a;this.ba=b;if(d){this.$=d;try{window.frameElement&&(window.frameElement.h=d)}catch(k){}}this.Xa(h);f&&this.Yb(f,G(arguments,9));p&&(this.b(2,window,"message",this.Xb),R("text/javascript",p));"loading"==document.readyState?this.fa=!0:this.Y()};e.wb=function(a){this.ga&&this.i&&(this.i=0,this.ja=window.setTimeout(this.da.bind(this,!1),3E3));this.Y(!0);a&&this.Xa();for(var b of w(this.c))this.pb(b)};
e.Xa=function(a){if(this.O(arguments)){var b=[21,this.ac||location.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.a.postMessage(b)}};e.Ab=function(a){var b=a?this.O(arguments):1;if(0<b||0>b&&1!=this.f){b=this.G();var c=this.V(),d=this.yb();this.a.postMessage([24,b,b&&b.src,c,d])}};e.Cb=function(a,b,c,d,f){c||(c=this.tb(b,d,f));d=(d=c&&this.c[c])&&this.L(d);this.a.postMessage([22,a,b,c,d])};e.zb=function(a,b){var c=
document.getElementsByTagName("a"),d;for(d of c)try{if(d.href==b){var f=d.download||null;var h=d.innerText.trim()||d.title||null;break}}catch(m){}this.a.postMessage([35,a,f,h])};e.Bb=function(a,b,c,d,f,h,m,l){if(this.O(arguments)){var p=[23,a,b,!1],k,g,q;if(b)b&&((k=this.c[b])||(p[3]=!0));else{if(k=this.ub(c,d,f,h,l,m)){if(this.ka&&(g=t(k,this.ka)))var n=200;else if(g=k.getAttribute("operadetachedviewtitle"))n=130;p[2]=b=k.l;p[5]=k.localName;p[6]=k.src||k.data}else if(l||m)p[3]=!0;!g&&(g=this.G())&&
(n=g.src,(q=aa.exec(g))&&(g=q[1]));p[7]=g;p[8]=n}k&&(g=this.L(k),null!=g||document.contains(k)?p[4]=g:(this.K(k),p[3]=!0));this.a.postMessage(p)}};e.xb=function(a,b,c,d){var f=d?RegExp(d,"i"):null;d=this.Va(document,f,b);var h=document.getElementsByTagName("iframe"),m;for(m of h)try{var l=m.contentDocument;l&&!m.src&&I(d,this.Va(l,f,b))}catch(p){}a=[27,a,this.$,d.length];c||(a[4]=d,a[5]=location.href,U&&(a[6]=location.href,a[7]=document.title));this.a.postMessage(a)};e.Va=function(a,b,c){var d=[],
f={},h="",m="",l=!c;if(c){var p=a.getSelection();if(!p||p.isCollapsed&&!p.toString().trim())return d}for(var k of a.getElementsByTagName("a"))if(l||p.containsNode(k,!0))try{var g=k.href;g&&!f[g]&&b.test(g)&&(f[g]=d.push([g,2,k.download||null,k.innerText.trim()||k.title]));c&&f[g]&&(m+=k.innerText,m+="\n")}catch(n){}for(k of a.getElementsByTagName("area"))if(l||p.containsNode(k,!0))try{(g=k.href)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,2,null,k.alt]))}catch(n){}for(k of a.getElementsByTagName("img"))if(l||
p.containsNode(k,!0))try{(g=k.src)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,3,null,"<<<=IDMTRANSMITIMGPREFIX=>>>"+k.alt])),l&&k.onclick&&(h+=k.onclick,h+="\n")}catch(n){}if(c){if(h=p.toString()){c=this.J(m);for(g of this.J(h))g&&!f[g]&&b.test(g)&&!c.includes(g)&&(f[g]=d.push([g,1]))}for(k of a.getElementsByTagName("textarea"))if(a=k.selectionStart,h=k.selectionEnd,(c=p.isCollapsed&&a<h)||p.containsNode(k,!0))try{var q=c?k.value.substring(a,h):k.value;for(g of this.J(q))g&&!f[g]&&b.test(g)&&(f[g]=d.push([g,
1]))}catch(n){}}else{for(k of a.getElementsByTagName("iframe"))try{(g=k.src)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,4]))}catch(n){}for(k of a.getElementsByTagName("script"))h+=k.innerText,h+="\n";if(h)for(g of this.J(h))g&&!f[g]&&b.test(g)&&(f[g]=d.push([g,5]))}return d};e.J=function(a){if(!this.gb){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(d){return this[d]}.bind({"%H":"\\w\\-\u00a0-\ufeff","%T":"\\w\\-.+*()$!,%\u00a0-\ufeff",
"%Q":"^\\s\\[\\]{}()"}));this.gb=RegExp(b,"gi")}for(var c=[];b=this.gb.exec(a);)c.push(b.shift());return c};e.O=function(a){var b=this.i;b||(a=E(a&&a.callee?a:arguments),a.unshift(arguments.callee.caller),this.aa.push(a));return b};e.$a=function(a){try{var b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.i=a&&b?-1:1;b&&(a=this.ga,a||(this.ga=a=new MutationObserver(this.da.bind(this))),a.observe(b,{childList:!0}));try{this.N=new ResizeObserver(this.ca.bind(this))}catch(c){}try{this.j=
new IntersectionObserver(this.ca.bind(this),{threshold:.2})}catch(c){}this.fa&&(this.fa=!1,this.Y());for(a=this.aa;b=a.shift();)b.shift().apply(this,b)};e.ca=function(a){if(this.a)for(var b of a)if(a=b.target,a.l)if(document.contains(a)){var c=b.isIntersecting;null!=c&&(a.W=!c,a.Db=c?b.intersectionRect:null);a.v&&window.clearTimeout(a.v);a.v=window.setTimeout(this.Mb.bind(this,a),200)}else this.a.postMessage([23,null,a.l,!0]),this.K(a)};e.Mb=function(a){if(!this.a)return this.K(a);a.v=null;var b=
document.contains(a);if(b){var c=this.L(a);if(1==this.f&&a.j)if(c){var d=t(a,this.S);d&&d.href&&d.href!=a.a&&this.A(a,null,d.href)}else a.a=a.c=null,b=!1}else this.K(a);this.a.postMessage([23,null,a.l,!b,c])};e.da=function(a){if(a)window.clearTimeout(this.ja),this.ja=window.setTimeout(this.da.bind(this,!1),1E3);else{0>this.i?this.i=1:++this.i;for(var b=this.aa;a=b.shift();)a.shift().apply(this,a)}};e.Lb=function(a){var b=a.target,c=b.localName;M(c)&&a.url&&(b=this.M(b),this.a.postMessage([25,b,c,
a.url]))};e.ab=function(a){!a.repeat&&L[a.keyCode]&&this.a.postMessage([31,a.keyCode,"keydown"==a.type])};e.Pb=function(a){this.nb&&this.a.postMessage([28]);if(0==a.button){var b=a.view.getSelection();b&&b.isCollapsed&&!b.toString().trim()&&(this.s=1);this.a.postMessage([32,a.button,!0])}};e.Rb=function(a){if(0==a.button){this.ha=a.clientX;this.ia=a.clientY;this.a.postMessage([32,a.button,!1]);var b=a.view.getSelection();b&&this.s&&(this.s=b.isCollapsed&&!b.toString().trim()?0:2)&&this.a.postMessage([26,
a.clientX,a.clientY,this.V()])}};e.Qb=function(){2==this.s&&(this.s=0)};e.Ob=function(a){a=a.target;"a"==a.localName&&this.a.postMessage([39,a.hasAttribute("download"),a.href,a.download])};e.Wb=function(){this.a.postMessage([29])};e.Vb=function(a){a=a.target;this.a.postMessage([30,a.innerWidth,a.innerHeight])};e.Nb=function(){this.s=0;this.a.postMessage([33])};e.b=function(a,b,c,d,f){var h=E(arguments);h[3]=d.bind(this);this.ea.push(h);0>a?(b=b[c],b.addListener.apply(b,h.slice(3))):b.addEventListener.apply(b,
h.slice(2))};e.cb=function(a){for(var b=this.ea,c=0;c<b.length;c++){var d=b[c][0];if(!a||a==d){var f=b.splice(c--,1).pop(),h=f.splice(0,2).pop();0>d?(h=h[f.shift()],h.removeListener.apply(h,f)):h.removeEventListener.apply(h,f)}}};e.Kb=function(a){X="youtube";Y="idmrs://youtube/";var b=this.Qa.exec(location.pathname+location.search);if(b){var c=t(document.body,this.Pa);c&&this.A(c,b[1])}if(!a){a=this.a;var d,f,h,m=0,l;for(l of document.getElementsByTagName("script")){if(l.src){if(b=this.I.exec(l.src))m|=
1,this.D[b[1]]?f=b[1]:c=l.src}else if(b=this.Oa.exec(l.textContent))m|=2,(h=parseInt(b[1],10))&&!this.D[h]&&(b=this.Ra.exec(l.textContent))&&(b=this.I.exec(b[1]))&&(d=V+b[0]);else if(this.Ja.test(l.textContent)){m|=4;var p=l.outerHTML}if(7==m)break}if(h||f)b={},b[118]=h,b[124]=f,a.postMessage([37,1,2,b]);a.postMessage([34,this.G(),null,p]);if(c||(c=d))d=new XMLHttpRequest,d.responseType="text",d.timeout=1E4,d.onreadystatechange=this.$b.bind(this,c,d),d.open("GET",c,!0),d.send();this.P=2}};e.$b=function(a,
b){if(4==b.readyState){var c=this.I.exec(a);if((a=(a=this.Ka.exec(b.response))&&parseInt(a[1]||a[2],10))&&(!this.D[a]||!this.D[c[1]])){var d=this.La.exec(b.response),f=this.Ma.exec(b.response);b=this.Na.exec(b.response);if(d&&f&&d[2]==f[1]){c=c&&c[1];var h={};h[118]=a;h[119]=d[0];h[120]=f[0];h[135]=b&&b[0];h[124]=c;this.a.postMessage([37,1,1,h])}}}};e.Gb=function d(b,c){b?(c&&b.shift().disconnect(),this.Z.disconnect(),this.fb.disconnect(),this.eb.clear()):(this.U(this.ra),this.Z=new MutationObserver(this.rb.bind(this)),
this.fb=new MutationObserver(this.qb.bind(this)),this.eb=new Set,this.P=3,this.m.startsWith("$")||(this.m="$<"+this.m.slice(1)+"<"),this.o.startsWith("$")||(this.o="$<"+this.o.slice(1)+"<"),this.B.startsWith("$")||(this.B="$*"+this.B),this.C.startsWith("$")||(this.C="$*"+this.C));if(c=this.kb=t(document.body,this.pa)){if(b=this.Z,b.observe(c,{childList:!0}),!this.Ua(c,!0)&&(c=t(c,this.qa))){var f=t(c,this.m);f&&b.observe(c,{childList:!0});b.observe(f||c.parentNode,{childList:!0})}}else!b&&(c=t(document.body,
this.ma))&&(f=new MutationObserver(d.bind(this,b=[])),b.push(f),f.observe(c,{childList:!0}))};e.Ua=function(b,c){var d=this.Z,f=this.m,h=this.B,m=this.fb,l=this.eb,p=0,k;for(k of t(b,h,[]))l.has(k)||t(k,h)||(l.add(k),m.observe(k,{childList:!0,subtree:!0}),c&&(b=t(k,f))&&(d.observe(b,{childList:!0}),p++),J(k.getElementsByTagName("video"),this.T.bind(this)));return p};e.rb=function(b){var c=this.kb,d;for(d of b){b=d.target.isSameNode(c);for(var f of d.addedNodes)1==f.nodeType&&this.Ua(f,b)}};e.qb=function(b){var c=
this.u,d=this.o,f;for(f of b)for(var h of f.addedNodes)if(1==h.nodeType)if(b=h.getElementsByTagName("video"),b.length)J(b,this.T.bind(this));else for(var m of c){b=m.shift();var l=t(b,d);l&&l.contains(h)&&this.T(b)}};e.T=function(b){if(!b.a){var c=t(b,this.o),d,f=c&&t(c,this.sa);if(!f){for(var h=this.la,m=this.oa,l=F.bind(["div","span","a"]),p,k,g,q,n,r=c;r&&m--&&l(r.localName);r=r.parentNode){var u=k=r,v=h+":scope:first-child:only-of-type";for(d=0;"<"==v[d];d++);d&&(v=v.slice(d));for(u=u.closest(v);u&&
d--;u=u.parentElement);if(d=u)break;if((g=r.previousSibling)&&"div"==g.localName){p||(p=r.querySelector('div[role="slider"]'));1==(n=r.querySelectorAll(h)).length?d=n[0]:(q=r.nextSibling)&&1==(n=q.querySelectorAll("ul:scope "+h)).length?d=n[0]:p&&1<(n=g.querySelectorAll(h)).length&&(d=n[n.length-1]);break}}!d&&k&&1==(n=t(k,this.C,[])).length&&(d=n[0]);!d&&c&&(d=c.querySelector(":scope >"+h));d&&(d=d.href);!d&&1==document.getElementsByTagName("video").length&&(f=this.na.exec(location.href))&&(f=f[1])}f||
d?this.A(b,f,d):this.bb(b,this.jb,this.sb.bind(this))}};e.sb=function(b,c){c&&this.A(b,c)};e.Hb=function(b){!b&&(this.U(this.ua),b=t(document.body,this.Ba))&&(B(b,this.va,this.Eb.bind(this)),B(b,this.ya,this.X.bind(this)),B(b,this.Ca,this.X.bind(this)),B(document.body,this.xa,this.X.bind(this)))};e.Ya=function(b,c,d){!c&&1==document.getElementsByTagName("video").length&&(c=this.wa.exec(location.href))&&(c=c[1]);this.A(b,c,d,!0)};e.Eb=function(b){for(var c of t(b,this.ta,[]))J(t(c,this.R,[]),this.Za.bind(this))};
e.X=function(b){J(t(b,this.R,[]),this.Za.bind(this))};e.Za=function(b){if(!b.a){var c=t(b,this.za);c?this.Ya(b,null,c):this.bb(b,this.Aa,this.Fb.bind(this))}};e.Fb=function(b,c){c&&this.Ya(b,c)};e.Jb=function(b){b||(this.U(this.Ea),(b=t(document.body,this.Ga))&&B(b,this.Ha,this.Zb.bind(this)))};e.Zb=function(b){if(b=t(b,this.Ia)){var c=this.Fa.exec(W);c&&this.A(b,c[1])}};e.Ib=function(b){if(!b){var c=t(document.body,this.mb);c&&(b=this.G(),c=c.outerHTML,this.a.postMessage([34,b,null,c.slice(0,c.indexOf(">")+
1)]))}};function R(b,c){var d=b.startsWith("image/")?"img":"script";d=document.createElement(d);d.src="data:"+b+";base64,"+c;d.onload=d.remove.bind(d);document.documentElement.appendChild(d)}function t(b,c,d){function f(q,n,r){for(;r&&n--;)r=r.parentElement;r&&(isNaN(q)||this.push(q),this.push(r));return r}if(!c)return d;var h,m,l=!0,p=d||[],k=c.split(O);1==k.length?(k[0].startsWith("<")&&k.unshift(k.shift().slice(1)+"<"),k.unshift(">",NaN)):k.shift();for(;b&&(h=k.shift());){c=parseInt(k.shift(),
10);var g=k.shift().trim();for(m=1;"<"==g[g.length-m];m++);--m&&(g=g.slice(0,-m).trim());switch(h){case "<":b=S(g?b.closest(g):b,m);l=!0;break;case ">":b=S(b.querySelector(g),m);l=!0;break;case "{":b.closest(g)&&(b=null);break;case "}":b.querySelector(g)&&(b=null);break;case "|":if(g=g.endsWith(":scope")?b.closest(g):b.querySelector(g))return g;l=!1;break;case "&":b=f.call(p,c,m,b.querySelector(g));l=!1;break;case "*":b.querySelectorAll(g).forEach(f.bind(p,c,m));l=!1;break;case "+":g=g?g.endsWith(":scope")?
b.closest(g):b.querySelector(g):b;f.call(p,c,m,g);l=!1;break;case "=":if(g=b.getAttribute(g))return g;l=!1;break;case "@":if(g=b.textContent.trim())return g;l=!1}}return p.length?p:l&&b||d}function B(b,c,d,f,h,m){if(null==f){f=t(b,c,[]);m=new MutationObserver(B.bind(null,b,c,d,f));m.observe(b,{childList:!0});for(var l of f)m.observe(l,{childList:!0});f.length&&d(f.F(-1))}else for(var p of h){for(var k of p.addedNodes)if(1==k.nodeType){h=t(b,c,[]).slice(f.length);var g=h.F(-1);if(g&&k.contains(g)){I(f,
h);for(l of h)m.observe(l,{childList:!0});for(var q of g.children)d(q)}else p.target.isSameNode(f.F(-1)||b)&&d(k)}for(k of p.removedNodes)if(1==k.nodeType)for(h=0;h<f.length;h++)if(k.contains(f[h])){f.splice(h);break}}}function S(b,c){for(;b&&c--;b=b.parentElement);return b}function ba(b,c){c&&(b[c]=!0);return b}var Z=Object.isExtensible;try{Z(null)}catch(b){Z=function(c){return c instanceof Object}}String.prototype.replaceAll||(String.prototype.replaceAll=function(b,c){return this.split(b).join(c)});
new P}!0;
