name: test_run_y
on:
  push:
  schedule:
    - cron:  '3 * * * *'

jobs:
  build:
    strategy:
      matrix:
        puisi: [a, b, c, d]  
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8'  # Specify the Python version you need, e.g., '3.8'

    - name: Get Google Chrome version
      id: chrome-version
      run: echo "::set-output name=version::$(choco search googlechrome --exact --limit-output | Select-String -Pattern '^googlechrome ' | ForEach-Object { $_.Line.Split()[1] })"
      shell: pwsh

    - name: Cache Google Chrome
      id: cache-chrome
      uses: actions/cache@v3
      with:
        path: C:\Program Files\Google\Chrome\Application
        key: google-chrome-${{ steps.chrome-version.outputs.version }}

    - name: Install Google Chrome using Chocolatey
      if: steps.cache-chrome.outputs.cache-hit != 'true'
      run: choco install googlechrome -y

    - name: Install pyautogui
      run: |
        pip install -r requirements.txt --quiet

    - name: run if puisi sama dengan a
      run: |        
        python main.py 1
      if: matrix.puisi == 'a'
    - name: run if puisi sama dengan b
      run: |        
        python main.py 2
      if: matrix.puisi == 'b'
    - name: run if puisi sama dengan c
      run: |        
        python main.py 3
      if: matrix.puisi == 'c'

    - name: run if puisi sama dengan d
      run: |
        python main.py 4
      if: matrix.puisi == 'd'
    - name: push if puisi sama dengan d
      run: |
        Rename-Item -path profiles -NewName a
        git add screenshot.png
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "Automated report"
        git push
      if: matrix.puisi == 'd'
